[[https://melpa.org/#/evil-tutor-sc][file:https://melpa.org/packages/evil-tutor-sc-badge.svg]]
[[https://stable.melpa.org/#/evil-tutor-sc][file:https://stable.melpa.org/packages/evil-tutor-sc-badge.svg]]
* evil-tutor-sc：简体中文的 Emacs Evil 实践式教程
An evil-tutor in Simplified Chinese.
** Credits
- This project is originally translated from [[https://github.com/syl20bnr/evil-tutor][evil-tutor]].
- Part of this project also comes from [[https://github.com/vim/vim/blob/master/runtime/tutor/tutor][vimtutor]] and Emacs Tutorial.
- =evil-tutor-sc.el= source code was originally modified from [[https://github.com/kenjimyzk/evil-tutor-ja][evil-tutor-ja.el]] .
- TOC of =README.org= was generated by [[https://github.com/alphapapa/org-make-toc][org-make-toc]].

** 目录
:PROPERTIES:
:TOC:      :include all
:END:
:CONTENTS:
- [[#描述][描述]]
- [[#安装][安装]]
- [[#使用][使用]]
- [[#致谢][致谢]]
:END:

** 描述
本项目是 Emacs Evil 的实践式教程，全面采用简体中文。
- 本项目原本译自 [[https://github.com/syl20bnr/evil-tutor][evil-tutor]]，
  除翻译之外的主要工作是大量的内容扩充、事实修正、术语统一、表意严谨化、功能改进、时效性维护与其他细节的打磨优化。

** 安装
从 MELPA 或 MELPA Stable 安装 evil-tutor-sc（注：它还具有两个依赖 [[https://www.emacswiki.org/emacs/Evil][evil]] 和 [[https://github.com/syl20bnr/evil-tutor][evil-tutor]]）即可正常使用本项目。

两者的主要区别是，在 MELPA 发布的是最新的开发版，在 MELPA Stable 发布的则是稳定版。
#+begin_quote
作为 MELPA 中的包，安装方法本来不必详述，但这里还是给出一段示例：
#+begin_src elisp
  (require 'package) ; 加载 package.el
  (setq package-check-signature nil) ; 是否检查签名
  ;; 配置镜像源
  (setq package-archives '(("gnu" . "https://mirrors.ustc.edu.cn/elpa/gnu/")
                           ("melpa" . "https://mirrors.ustc.edu.cn/elpa/melpa/")))
  ;; 自动安装 use-package；在 Emacs 29 中已内置故可省略
  (unless (package-installed-p 'use-package) (package-install 'use-package))
  ;; 自动安装所有使用 use-package 声明的插件
  (require 'use-package-ensure)
  (setq use-package-always-ensure t)
  ;; 安装 evil-tutor-sc
  (use-package evil-tutor-sc)
#+end_src
注：一份可供 Emacs 新手使用的 Emacs 配置（包含了 evil、evil-collection 及 evil-tutor-sc 等）也可参考 [[https://github.com/clsty/arCNiso/tree/main/homebase/public/.emacs.d][arCNiso 中的 .emacs.d]] 。
#+end_quote

** 使用
一、要进入教程（若上次教程会话存在，则继续此会话）：
#+begin_example
M-x evil-tutor-sc-start
#+end_example
#+begin_quote
这会在临时目录 =evil-tutor-sc-working-directory=
（对于 \ast{}nix 系统，默认为 =~/.emacs.d/.tutor-sc= ）创建一个工作文件来保存会话。
#+end_quote

二、（无论上次教程会话是否存在）要进入一个全新的教程：
#+begin_example
M-x evil-tutor-sc-start-new
#+end_example

三、通过 =C-j= 与 =C-k= ，可在课程之间快速导航。

** 致谢
- 本项目原本译自 [[https://github.com/syl20bnr/evil-tutor][evil-tutor]]。
- 部分内容也来源于 [[https://github.com/vim/vim/blob/master/runtime/tutor/tutor][vimtutor]] 与 Emacs Tutorial。
- =evil-tutor-sc.el= 代码原本来自 [[https://github.com/kenjimyzk/evil-tutor-ja][evil-tutor-ja.el]]。
- 自述文档的目录由 [[https://github.com/alphapapa/org-make-toc][org-make-toc]] 辅助完成。
